### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by enkrypt3d** [magico13/ha-emporia-vue#110]
```
2022-03-04 20:43:48 INFO (MainThread) [custom_components.emporia_vue.sensor] {'vue_data': <pyemvue.pyemvue.PyEmVue object at 0xb0a0a5c8>, 'coordinator_1min': <homeassistant.helpers.update_coordinator.DataUpdateCoordinator object at 0xb0a0a640>, 'coordinator_1hr': <homeassistant.helpers.update_coordinator.DataUpdateCoordinator object at 0xaade0088>, 'coordinator_day_sensor': <homeassistant.helpers.update_coordinator.DataUpdateCoordinator object at 0xa995bfe8>}
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.home_123_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.mainsfromgrid_mainsfromgrid_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.mainstogrid_mainstogrid_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dryer_1_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.drop_in_2_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dryer_3_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.drop_in_4_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_5_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_6_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_7_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_8_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hot_water_heater_9_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.totalusage_totalusage_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.home_balance_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.none_123_1mon (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.home_123_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.mainsfromgrid_mainsfromgrid_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.mainstogrid_mainstogrid_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dryer_1_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.drop_in_2_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dryer_3_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.drop_in_4_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_5_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_6_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_7_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hvac_8_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hot_water_heater_9_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.totalusage_totalusage_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.home_balance_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:48 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.none_123_1d (<class 'custom_components.emporia_vue.sensor.CurrentVuePowerSensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.
2022-03-04 20:43:49 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.enphase_envoy
2022-03-04 20:43:49 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform emporia_vue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/emporia_vue/switch.py", line 131, in device_info
    "name": self._device.device_name+'-1,2,3',
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2022-03-04 20:43:49 ERROR (MainThread) [homeassistant.components.switch] Error while setting up emporia_vue platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/emporia_vue/switch.py", line 131, in device_info
    "name": self._device.device_name+'-1,2,3',
```

Getting these errors in the logs. Running Home Assistant 2022.2.9. Let me know if I can provide more details. thanks!

**Comment by magico13** [comment]
Thanks for the report! All of the ones mentioning last_reset can safely be ignored for now, I'm planning on swapping off of total_increasing and will actually need to update the last_reset calculation when doing so.

The errors toward the bottom with setting up the switch is a new one. If I had to guess what would cause that, you have an outlet that has no name defined in the Emporia app. If that's the case, it's not something I had considered. I'll have to think about how to handle that in the future but you could probably get rid of that error by naming it. If you don't have any unnamed outlets then that's extra strange.

**Comment by enkrypt3d** [comment]
ah ok I had an old smart outlet that wasn't working so I removed that. so hopefully it should clear up some of the noise. As far as updating, will it be included in HA core or HACS? thanks!

**Comment by magico13** [comment]
For now this is only going to be in HACS but there's a chance I try to get it into HA core one of these days.

**Comment by enkrypt3d** [comment]
Sounds great thanks again!

**Comment by enkrypt3d** [comment]
Last question for you, why are these 2 entities different? shouldn't they be the same? 

![image](https://user-images.githubusercontent.com/93238214/156941052-f6401ec4-e83c-4bc6-bb5a-a9d68339f23e.png)

**Comment by magico13** [comment]
Balance is the difference between what's measured at the main breaker and the monitored circuits. For a basic setup with no solar, it's the Mains minus all the individual sensors. How it works with solar might be a bit different, I can't say because I don't have solar unfortunately. It should correspond to the Balance at the bottom of the app.

![Screenshot_20220306-154001](https://user-images.githubusercontent.com/5289685/156941371-4e9f5a0b-9118-481f-a674-373ea43c6bc3.png)

**Comment by enkrypt3d** [comment]
Ok so I have extensions so that I can put the 200A CT's on the mains in
front of the hot tub which has taps just behind the main breaker. and then
the main panel which is fed by solar & battery backup is where the emporia
vue is. so the difference would be the hot tub circuit then since it does
not have direct monitoring? Hopefully that makes sense...

**Comment by enkrypt3d** [comment]
![image](https://user-images.githubusercontent.com/93238214/156941837-6bf8ee3d-71da-4631-b00c-ac9304405475.png)

May help the illustration. hot tub is on top and you can see when it runs... and when I'm exporting to the grid after my batteries are charged up.

**Comment by enkrypt3d** [comment]
What can I do to get rid of these errors?
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:331
Integration: Sensor (documentation, issues)
First occurred: 3:25:10 PM (3 occurrences)
Last logged: 3:50:10 PM

Entity sensor.home_123_1mon from integration emporia_vue has state class total_increasing, but its state is negative. Triggered by state -17.399 with last_updated set to 2022-04-07T19:19:59.999999+00:00. Please report it to the custom component author.
Entity sensor.home_balance_1mon from integration emporia_vue has state class total_increasing, but its state is negative. Triggered by state -174.89 with last_updated set to 2022-04-07T19:19:59.999999+00:00. Please report it to the custom component author.
Entity sensor.home_balance_1d from integration emporia_vue has state class total_increasing, but its state is negative. Triggered by state -0.007 with last_updated set to 2022-04-07T19:49:03.003639+00:00. Please report it to the custom component author.

**Comment by magico13** [comment]
Currently there's nothing you can do. I'm testing a change where the state class is changed to `total` and I have some other things I'm going to be testing in the near future that will also fix this.

**Comment by enkrypt3d** [comment]
Sounds great! Let me know if you need someone to test. Thanks!

**Comment by enkrypt3d** [comment]
Is there a way to make the "mainstogrid" entity read a negative value instead of positive when it is exporting to the grid? This would reflect net metering a bit more accurately....

**Comment by magico13** [comment]
I believe the Home Assistant dashboard requires it to be positive, at least it definitely used to, since I had to flip the sign between the API and the sensor to get it to work properly for other people. You could set up a template sensor that flips the sign to negative if you wanted it that way but I don't believe that it'll operate correctly as the "export" sensor in the energy dashboard, unless they updated that.

**Comment by cybernard** [comment]
I have the same error  with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author

Also regarding negative values because solar panels generate power I want to have negative values registered as power generation.

**Comment by magico13** [comment]
There's a pre-release available that includes a change from `total_increasing` to `total` if you're willing to try out "beta" versions. It fixes these error messages and behaves better when the API gives bad data and then corrects itself later. I still have a couple fixes I intend to put in there so that's the main reason it hasn't been promoted to a full release.

**Comment by trickiegt** [comment]
Bump & Thanks for the hard work and effort!
