### ISSUE TITLE
Errors in Logs after Recent Update

### ISSUE THREAD

**Issue by Imburr** [magico13/ha-emporia-vue#111]
I just went to check my logs and found quite a few from this integration, I assume they started with the recent update, which I applied yesterday. With that said, thanks for maintaining this, great integration!

`
Logger: homeassistant
Source: custom_components/emporia_vue/sensor.py:90
Integration: Emporia Vue (documentation)
First occurred: 10:41:01 AM (1 occurrences)
Last logged: 10:41:01 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/emporia_vue/sensor.py", line 90, in state
    usage = self.coordinator.data[self._id]["usage"]
KeyError: '52534-1-1MIN'

Logger: custom_components.emporia_vue.switch
Source: helpers/update_coordinator.py:219
Integration: Emporia Vue (documentation)
First occurred: 8:43:14 AM (1 occurrences)
Last logged: 8:43:14 AM

Error fetching switch data: Error communicating with Emporia API: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/customers/devices/status

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:263
Integration: Emporia Vue (documentation)
First occurred: 12:25:10 AM (3 occurrences)
Last logged: 3:40:18 PM

Error communicating with Emporia API: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/AppAPI?apiMethod=getDeviceListUsages&deviceGids=52515+52522+52532+52534+52572+52595+52598+52613+52722+91602&instant=2022-03-07T05:25:10.001742Z&scale=1MIN&energyUnit=KilowattHours
Error communicating with Emporia API: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/AppAPI?apiMethod=getDeviceListUsages&deviceGids=52515+52522+52532+52534+52572+52595+52598+52613+52722+91602&instant=2022-03-07T15:40:01.002580Z&scale=1MIN&energyUnit=KilowattHours
Error communicating with Emporia API: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/AppAPI?apiMethod=getDeviceListUsages&deviceGids=52515+52522+52532+52534+52572+52595+52598+52613+52722+91602&instant=2022-03-07T20:40:18.001974Z&scale=1MIN&energyUnit=KilowattHours
`

**Comment by jfroy** [comment]
I've been some 500 errors daily as well.

**Comment by magico13** [comment]
Unfortunately I can't do much about the 500s, that's a response from their API and is a result of their own instability. For instance I had a boat load of bad responses yesterday and during that time their app was reporting all my devices as offline when looking at the second and minute data but working fine when looking at the hour and longer data.

**Comment by jfroy** [comment]
Yes, I saw that too! I also concluded it was their API that was flaking out -- connectivity to the device and to the meter, as far as I could tell, was fine. It's a shame there's no local API (as it always is with home automation products -- https://arstechnica.com/gadgets/2022/04/shameful-insteon-looks-dead-just-like-its-users-smart-homes/ was a recent good reminder).
