### ISSUE TITLE
Errors in Log

### ISSUE THREAD

**Issue by pmd5700** [magico13/ha-emporia-vue#118]
I've recently started getting these errors. I upgraded to the most recent version of HA, but the Emporia Vue was also ofline for a while. It's back online now, but I still get these errors:

`2022-04-08 10:37:18 INFO (MainThread) [custom_components.emporia_vue] Found 2 Emporia devices with 9 total channels
2022-04-08 10:37:18 INFO (MainThread) [custom_components.emporia_vue] Adding channel for channel 12075-Balance
2022-04-08 10:37:18 INFO (MainThread) [custom_components.emporia_vue] 1min Update data: {'12075-1,2,3-1MIN': {'device_gid': 12075, 'channel_num': '1,2,3', 'usage': 0.03862290305667453, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-1-1MIN': {'device_gid': 12075, 'channel_num': '1', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-2-1MIN': {'device_gid': 12075, 'channel_num': '2', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-3-1MIN': {'device_gid': 12075, 'channel_num': '3', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-4-1MIN': {'device_gid': 12075, 'channel_num': '4', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-5-1MIN': {'device_gid': 12075, 'channel_num': '5', 'usage': 0.003475866998434067, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-6-1MIN': {'device_gid': 12075, 'channel_num': '6', 'usage': 0.0035007751763529243, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}, '12075-Balance-1MIN': {'device_gid': 12075, 'channel_num': 'Balance', 'usage': 0.031646260881887545, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': None}}
2022-04-08 10:37:18 INFO (MainThread) [custom_components.emporia_vue] 1hr Update data: {'12075-1,2,3-1MON': {'device_gid': 12075, 'channel_num': '1,2,3', 'usage': 314.54856271295125, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-1-1MON': {'device_gid': 12075, 'channel_num': '1', 'usage': 28.052026055579713, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-2-1MON': {'device_gid': 12075, 'channel_num': '2', 'usage': 27.791871031718784, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-3-1MON': {'device_gid': 12075, 'channel_num': '3', 'usage': 69.85045586187469, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-4-1MON': {'device_gid': 12075, 'channel_num': '4', 'usage': 69.96228292952115, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-5-1MON': {'device_gid': 12075, 'channel_num': '5', 'usage': 11.75668718528105, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-6-1MON': {'device_gid': 12075, 'channel_num': '6', 'usage': 11.804020259355902, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}, '12075-Balance-1MON': {'device_gid': 12075, 'channel_num': 'Balance', 'usage': 95.33121938961995, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x7fed75289a90>, 'reset': datetime.datetime(2022, 4, 8, 14, 37, 18, tzinfo=tzutc())}}
2022-04-08 10:37:18 INFO (MainThread) [custom_components.emporia_vue] Integrating minute data into day sensors
2022-04-08 10:37:18 ERROR (MainThread) [custom_components.emporia_vue] Unexpected error fetching sensor data: '12075-1-1D'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
return await self.update_method()
File "/config/custom_components/emporia_vue/__init__.py", line 149, in async_update_day_sensors
and last_day_data[day_id]
KeyError: '12075-1-1D'
2022-04-08 10:37:18 WARNING (MainThread) [custom_components.emporia_vue] Exception while setting up Emporia Vue. Will retry. '12075-1-1D'`

**Comment by magico13** [comment]
It's sort of weird that you see the INFO messages since those are usually disabled. They're mostly for debugging purposes so you can safely ignore those. The key error should be resolved with an update that I'm still doing testing on.

**Comment by oziee** [comment]
@magico13 any idea when we might see a new update to fix all the problems?
