### ISSUE TITLE
Unexpected exception during setup

### ISSUE THREAD

**Issue by jmayes2** [magico13/ha-emporia-vue#120]
I just upgraded to 8.0 just to get the vue integration and when I try to register I get this;

Logger: custom_components.emporia_vue.config_flow
Source: config_entries.py:916
Integration: Emporia Vue ([documentation](https://github.com/magico13/ha-emporia-vue))
First occurred: 3:44:32 PM (3 occurrences)
Last logged: 5:54:52 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 80, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 916, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow("already_configured")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

Any help would be wonderful!
J

**Comment by jmayes2** [comment]
Just found it, the integration was already added, did not know it was there, deleted and it reinstalled correctly.
