### ISSUE TITLE
"unknown error" when trying to sign in.

### ISSUE THREAD

**Issue by deverox-GHT** [magico13/ha-emporia-vue#129]
I keep getting a red "unknown error" when trying to sign in.  Am I missing something obvious?

**Comment by Francois1976** [comment]
Same here.  Thk

**Comment by deverox-GHT** [comment]
I was able to fix the problem by upgrading my server.  Previously I was
running on a Pi4 (2GB ram) with MicroSD Card running home assistant.
When I was having issues I switched it to a Pi4 4GB and put it on a SSD.
Now works like a dream.

**Comment by nad22** [comment]
I have the same issue, vue was working before but sometimes the sensors are displayed "unavailable" after a integration restart all is ok until next unavailable state. Today i could not reload the integraiton so i reinstalled it but now i cannot login anymore gettingg ghe "unknown error". This should not be a problem with my server because it worked yesterday

**Comment by deverox-GHT** [comment]
Did you install something yesterday that could be slowing the server down?

**Comment by ZinTheDog** [comment]
I'm getting this too on a first time install (v0.8).  Red "Unexpected error"

**Comment by deverox-GHT** [comment]
I solved it by upgrading the hardware HA was running on.

**Comment by ZinTheDog** [comment]
My resource utilization is very low.  I'm running HA on a VM with quite a bit of hardware resources behind it.

**Comment by fasavard** [comment]
Same problem over here, 
i updated the emporia app and have the issue of an infinite loop when upgrading, 
had to do this to fix the issue
https://www.reddit.com/r/homeassistant/comments/ti1k43/hacs_update_failing_hacs_v1160_ha_v202235/

but now i get the unknow error. Is there somewhere emporia store log ? In the main log there is nothing show related to this

**Comment by fasavard** [comment]
Alraight been able to find a log. I wasent getting anything from my workstation but when trying from my iphone i finally get an uncought error. 
`2022-12-05 06:12:12.746 ERROR (MainThread) [custom_components.emporia_vue.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 77, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/emporia_vue/config_flow.py", line 48, in validate_input
    if not await hub.authenticate(data[CONF_EMAIL], data[CONF_PASSWORD]):
  File "/config/custom_components/emporia_vue/config_flow.py", line 38, in authenticate
    result = await loop.run_in_executor(None, self.vue.login, username, password)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyemvue/pyemvue.py", line 207, in login
    self.auth = Auth(
  File "/usr/local/lib/python3.10/site-packages/pyemvue/auth.py", line 49, in __init__
    self.cognito.authenticate(password=password)
  File "/usr/local/lib/python3.10/site-packages/pycognito/__init__.py", line 463, in authenticate
    tokens = aws.authenticate_user(client_metadata=client_metadata)
  File "/usr/local/lib/python3.10/site-packages/pycognito/aws_srp.py", line 267, in authenticate_user
    response = boto_client.initiate_auth(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UserNotFoundException: An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.`

Currently looking on why my user is non-existing. I double chek the credential and everything was fine

**Comment by ZinTheDog** [comment]
Mine ended up being a case sensitivity issue on the email address!!  The email address I saved had a capital letter as the first letter, but the address registered with Emporia was all lowercase.  I double checked on the Emporia web view under account settings to see how my email was written, matched that by using all lowercase and now I'm logged in.

**Comment by fasavard** [comment]
Good to know, i'll look to do a pull request if a got time to force lowercase email
