### ISSUE TITLE
Updating of sensors sometimes stops working

### ISSUE THREAD

**Issue by skynet01** [magico13/ha-emporia-vue#13]
This happened to me a few times. Basically, the sensors stop updating the only thing i found in the log is this:

```
Logger: homeassistant.helpers.entity
Source: custom_components/emporia_vue/sensor.py:73
First occurred: 12:43:35 AM (1 occurrences)
Last logged: 12:43:35 AM

Update for sensor.power_living_room_ac_3 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/emporia_vue/sensor.py", line 73, in update
    channels = self._vue.get_recent_usage(scale=Scale.MINUTE.value)
  File "/usr/local/lib/python3.8/site-packages/pyemvue/pyemvue.py", line 97, in get_recent_usage
    response = self._get_request(url)
  File "/usr/local/lib/python3.8/site-packages/pyemvue/pyemvue.py", line 161, in _get_request
    return requests.get(full_endpoint, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Let me know if there is any other information i can provide.

**Comment by skynet01** [comment]
I think what might be happening is the API goes does for a bit and then when plugin trys to reconnect it's no longer authorized to do so. Restarting Home Assistant fixes the issue. It always consistently happens at night and the first error i get is this 

```
Logger: homeassistant.helpers.entity
Source: custom_components/emporia_vue/sensor.py:73
First occurred: October 3, 2020, 5:12:55 PM (3 occurrences)
Last logged: 2:17:57 AM

Update for sensor.power_hallway_ac_1 fails
Update for sensor.power_pelican_123 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/emporia_vue/sensor.py", line 73, in update
    channels = self._vue.get_recent_usage(scale=Scale.MINUTE.value)
  File "/usr/local/lib/python3.8/site-packages/pyemvue/pyemvue.py", line 98, in get_recent_usage
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://api.emporiaenergy.com/usage/devices?start=2020-10-04T00:12:25.524821Z&end=2020-10-04T00:12:26.524821Z&scale=1MIN&unit=WATTS&customerGid=10640
```
When I try the above URL manually I no longer get time-out error but an Unauthorized error. Is there a way to maybe reauthenticate the connection after time out is detected?

**Comment by magico13** [comment]
It might be as simple as me catching the exception since the library should always try to reauthenticate if the token isn't valid anymore. I think the exception is making home assistant not try to it update again. I also can probably add detection of intentional downtime to the library since I know how they tell the app about that. I think this is pretty fixable so I'll try to take care of it next time I make updates to this (which will probably be soonish since I added support for their smart outlets to the library and want to add them to home assistant as well)

**Comment by skynet01** [comment]
Awesome! Yeah cause right now the sensors just get stuck on the last value so it throws off all the utility calculation data. Thank you so much for checking it out.

**Comment by skynet01** [comment]
Here is more from my logs, today it was a 500 server error instead of 504.
```
Logger: homeassistant.helpers.entity
Source: custom_components/emporia_vue/sensor.py:73
First occurred: October 6, 2020, 11:00:15 AM (10 occurrences)
Last logged: October 7, 2020, 6:01:01 PM

Update for sensor.power_pelican_123 fails
Update for sensor.power_dryer_4 fails
Update for sensor.power_lounge_patio_2 fails
Update for sensor.power_hallway_ac_1 fails
Update for sensor.power_fridge_5 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/emporia_vue/sensor.py", line 73, in update
    channels = self._vue.get_recent_usage(scale=Scale.MINUTE.value)
  File "/usr/local/lib/python3.8/site-packages/pyemvue/pyemvue.py", line 98, in get_recent_usage
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.emporiaenergy.com/usage/devices?start=2020-10-06T18:00:14.809893Z&end=2020-10-06T18:00:15.809893Z&scale=1MIN&unit=WATTS&customerGid=10640
```

**Comment by magico13** [comment]
I'm curious if my changes in v0.2.0 might avert this problem. If anyone sees this still with that update let me know. If we don't have any reports in about a month I'll consider this fixed.

**Comment by skynet01** [comment]
ill be on the watch out for it, thanks for the fix! I think their service is more stable now as well as i haven't had the timeout for a few weeks now.

**Comment by magico13** [comment]
I'm doing some cleanup and am going to close this issue. Please open another if any new issues come up!
