### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by mmahoneynv** [magico13/ha-emporia-vue#163]
Hi.  Getting this error when trying to connect:
-----------------------
2022-11-25 08:44:34.656 ERROR (MainThread) [custom_components.emporia_vue.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 80, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1368, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured
-----------------------

Explanation:  I had an Emporia Unit with this link activated, the solar company swapped it for a Curb unit, and now because of my complaining they have brought another Emporia Unit.  I'm using my same email address as before.

**Comment by Thatindianbruh** [comment]
Just happened to me. Email AND password are Case ID.

**Comment by magico13** [comment]
If you have an inactive device on your account try fully removing that and then trying again. Double check that your credentials are correct and are the ones for the app and not the ones for the forums.

The error specifically mentioned above is that the integration is already set up according to Home Assistant, so make sure you've fully removed the integration before installing it again. Maybe give it a restart or two to make sure it's really removed.

**Comment by mmahoneynv** [comment]
Thank you Magico13.  That worked!
