### ISSUE TITLE
Just stopped working

### ISSUE THREAD

**Issue by josephny** [magico13/ha-emporia-vue#198]
All of a sudden (today) this integration stopped working with an error of:

Could not authenticate with Emporia API

Running HA 2023.5.0; supervisor 2023.04.1, OS 10.1

I tried installing it on another HA server  (2023.4.2, supervisor 2023.4.1; OS 9.5) at another location and I could not get past the email/psswd login request.

I am able to login to Emporia's web portal.

Any ideas?

Thank you.

**Comment by magico13** [comment]
I haven't upgraded to 2023.5 yet so it's possible there's a dependency conflict causing this. Otherwise this is usually due to extra spaces in the email address field or putting a capital letter in the email address, since the API expects all lowercase.

**Comment by josephny** [comment]
It started working again.

Still running the same HA versions.

Restarted HA about 20 times.  Then gave up and a bunch of hours later it started working.

**Comment by josephny** [comment]
And today's it's not working again.

Same error:

Could not authenticate with Emporia API

**Comment by degreal** [comment]
Updating stalls about every 4 days. Reload button under integration always fixes the problem.

**Comment by oooshk** [comment]
Same here, could not authenticate with emporia API.  Several times a day, but it does connect sporadically.

**Comment by josephny** [comment]
Exactly.  Works for a few days, then stops, then works for a few days, then stop.

**Comment by oooshk** [comment]
> Exactly. Works for a few days, then stops, then works for a few days, then stop.

I asked emporia directly if they had plans to release an off net solution that doesn't mean I have to risk bricking my device.  They couldn't answer that, but they did mention they plan to launch a HA integration themselves at some point.

**Comment by josephny** [comment]
> > Exactly. Works for a few days, then stops, then works for a few days, then stop.
> 
> I asked emporia directly if they had plans to release an off net solution that doesn't mean I have to risk bricking my device. They couldn't answer that, but they did mention they plan to launch a HA integration themselves at some point.

Thanks for reaching out to them.  I hope they do, but I would not be surprised if it doesn't happen anytime soon.

I still have no functionality.

Integration fails with:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/emporia_vue/__init__.py:94
Integration: Emporia Vue (documentation, issues)
First occurred: May 29, 2023 at 10:16:21 PM (1 occurrences)
Last logged: May 29, 2023 at 10:16:21 PM

Error setting up entry Customer 1665 for emporia_vue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/emporia_vue/__init__.py", line 94, in async_setup_entry
    result = await loop.run_in_executor(None, vue.login, email, password)
asyncio.exceptions.CancelledError

**Comment by greggitter** [comment]
Same issue, maybe custom firmware is the way to go.  It seems like Emporia could provide a json page locally to solve these issues...or is not that simple...?  I appreciate the addon and support @magico13...thanks.

**Comment by jmunowitch** [comment]
I encountered this as well.

I ended up changing my password with Emporia to be no special characters, and uninstalled and reinstalled `ha-emporia-vue`. It is working now.

**Comment by greggitter** [comment]
Yesterday morning (EDT) for a period of time, their service appeared offline, their app also wouldn't work.  Later it came back and HA reconnected (I have an automation to reload the integration every 15 minutes if unavailable).  Again this morning though, HA is not working with it, but the app is working fine.  It's getting more tempting to just flash with the custom firmware and run local and be done with their cloud service.  Checking just now, it looks like the total usage stat is showing, just none of the individual circuits...they read "unavailable".

On a side note, was looking to buy one of their EV chargers but due to their lack of opening/creating a local API I decided against it.
