### ISSUE TITLE
The integration stopped working since the outage...

### ISSUE THREAD

**Issue by sh0ckwavevr6** [magico13/ha-emporia-vue#235]
So the Emporia addon for HA stopped working last weekend. when I enter my User and password to connect on the API I got an error message and the following error is logged in the debug trace.

```
023-11-22 08:29:54.794 ERROR (MainThread) [custom_components.emporia_vue.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 80, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1597, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured
2023-11-22 08:30:13.897 ERROR (MainThread) [custom_components.emporia_vue.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 80, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1597, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
```

**Comment by magico13** [comment]
Already configured implies it's already set up. Have you restarted Home Assistant? If not, try that and it might appear without any other input. Otherwise I'm not sure off hand how to remove the already configured one, if it comes to that then we can figure that out.
