### ISSUE TITLE
Adding credentials doesn't work

### ISSUE THREAD

**Issue by GChan21** [magico13/ha-emporia-vue#245]
Hi, thanks for creating this, videos online look great!  My installation seemed to go fine until i add my email and password i use for Emporia.  I then get a spinning wheel and it never completes the install.  Eventually it times out with "Unexpected Error".  Any ideas?  
Thanks!

**Comment by sruohonen** [comment]
Same issue for my installation - any advice?

**Comment by yuri-tceretian** [comment]
I have similar problem. After upgrading to the latest version of plugin it started failing to authorize.
The logs show 
```
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 76, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 47, in validate_input
    if not await hub.authenticate(data[CONF_EMAIL], data[CONF_PASSWORD]):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 37, in authenticate
    result = await loop.run_in_executor(None, self.vue.login, username, password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/pyemvue.py", line 355, in login
    self.auth = Auth(
                ^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/auth.py", line 57, in __init__
    self.cognito.authenticate(password=password)
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 495, in authenticate
    self._set_tokens(tokens)
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 767, in _set_tokens
    self.verify_token(
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 266, in verify_token
    raise TokenVerificationException(
pycognito.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat)).
```

**Comment by magico13** [comment]
@yuri-tceretian your issue is from your server time drifting too far from reality, see #260. The original error for this issue was likely an outage on the Emporia/AWS side or invalid credentials, @GChan21 did you ever get logged in?

**Comment by GChan21** [comment]
@magico13 , thanks for the reply. I haven't managed to log in yet, but I've not tried for a while. 
I'll give it another go and keep you posted. 
Cheers!

**Comment by RageInvader** [comment]
I'm getting same error, cant connect anymore

**Comment by DabblerIOT** [comment]
Token not yet valid typically means your time on your ha instance or docker containers is wrong.

**Comment by RageInvader** [comment]
yeah i have checked and made sure time is correct, could it be daylight savings in the uk?

**Comment by DabblerIOT** [comment]
Don't know, your os and all that up to date?   Servers are in iad... us east for auth..  time changed here a couple weeks ago.

Where are you trying to authenticate from?

**Comment by DabblerIOT** [comment]
reboot host and see how it pans out?   Hopefully time sync sorts it all out?

**Comment by RageInvader** [comment]
I'm running in a docker on unraid. tried all the reboots nothing helping.

**Comment by RageInvader** [comment]
okay, i tried changing timezone on unraid to UTC which takes my clock 1 hour back, and it works now.

**Comment by sushain97** [comment]
I'm seeing this issue and unfortunately an NTP sync doesn't fix it.

That is, after running:
```
home:~# ntpd -d -q -n -p pool.ntp.org
ntpd: 'pool.ntp.org' is 198.60.22.240
ntpd: sending query to 198.60.22.240
ntpd: reply from 198.60.22.240: offset:+0.976274 delay:0.026299 status:0x24 strat:2 refid:0x0260a384 rootdelay:0.014282 reach:0x01
ntpd: sending query to 198.60.22.240
ntpd: reply from 198.60.22.240: offset:+0.976367 delay:0.026415 status:0x24 strat:2 refid:0x0260a384 rootdelay:0.014282 reach:0x03
```

I'm still seeing this error:
```
pycognito.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat)).
```

My HA container is configured to use PDT:
```
home:/config# env | grep TZ
TZ=America/Los_Angeles
home:/config# date
Tue Apr  9 23:11:28 PDT 2024
```
