### ISSUE TITLE
Token is not yet valid

### ISSUE THREAD

**Issue by Flo2830** [magico13/ha-emporia-vue#260]
**It has recently become impossible to log in. Uninstalling and reinstalling the integration but no change:**

Version: 0.9.2

Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:76
Integration: emporia_vue ([documentation](https://github.com/magico13/ha-emporia-vue), [issues](https://github.com/magico13/ha-emporia-vue/issues))
First occurred: 18:32:07 (1 occurrences)
Last logged: 18:32:07

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 76, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 47, in validate_input
    if not await hub.authenticate(data[CONF_EMAIL], data[CONF_PASSWORD]):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/config_flow.py", line 37, in authenticate
    result = await loop.run_in_executor(None, self.vue.login, username, password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/pyemvue.py", line 276, in login
    self.auth = Auth(
                ^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/auth.py", line 49, in __init__
    self.tokens = self.refresh_tokens()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyemvue/auth.py", line 53, in refresh_tokens
    self.cognito.renew_access_token()
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 695, in renew_access_token
    self._set_tokens(refresh_response)
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 767, in _set_tokens
    self.verify_token(
  File "/usr/local/lib/python3.12/site-packages/pycognito/__init__.py", line 266, in verify_token
    raise TokenVerificationException(
pycognito.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat))

**Comment by magico13** [comment]
The change to pyJWT for token validation within pycognito has made the clock requirements more stringent and I haven't found a way to loosen them. The short of it is that your server time is likely a few seconds behind reality, force an NTP sync and then try again.

**Comment by Flo2830** [comment]
thank you very much for this quick response, I'll check the NTP sync right away.

**Comment by Flo2830** [comment]
Force NTP sync by reboot VM Home assistant and connection success.
Thanks Magico13
