### ISSUE TITLE
Unexpected Error when trying to login 

### ISSUE THREAD

**Issue by adamtar** [magico13/ha-emporia-vue#296]
Hello,
I just installed the integration. I am getting an unexpected error when logging in under the service section. Has anyone else seen this? Any fix? Thanks in advance.

**Comment by kilbyjmichael** [comment]
I am also getting this error. See logs below. After retrying the setup it claims it is already set up but still does not work.

```
Logger: custom_components.emporia_vue.config_flow
Source: custom_components/emporia_vue/config_flow.py:79
integration: Emporia Vue ([documentation](https://github.com/magico13/ha-emporia-vue), [issues](https://github.com/magico13/ha-emporia-vue/issues))
First occurred: 9:23:53 AM (1 occurrences)
Last logged: 9:23:53 AM
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/emporia_vue/config_flow.py", line 79, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2333, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured
```


```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 9:23:36 AM (1 occurrences)
Last logged: 9:23:36 AM
Error setting up entry Customer XXXXXX for emporia_vue

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/__init__.py", line 212, in async_setup_entry
    await coordinator_day_sensor.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/__init__.py", line 149, in async_update_day_sensors
    LAST_DAY_DATA = await update_sensors(vue, [Scale.DAY.value])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/emporia_vue/__init__.py", line 361, in update_sensors
    usage_dict = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 9:22:44 AM (1 occurrences)
Last logged: 9:22:44 AM
Detected blocking call to open with args ('/usr/share/zoneinfo/America/Chicago', 'rb') inside the event loop by custom integration 'emporia_vue' at custom_components/emporia_vue/__init__.py, line 564: tz_info = dateutil.tz.gettz(tz_string) (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/magico13/ha-emporia-vue/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/emporia_vue/__init__.py", line 185, in async_setup_entry await coordinator_1min.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/emporia_vue/__init__.py", line 126, in async_update_data_1min data = await update_sensors(vue, [Scale.MINUTE.value]) File "/config/custom_components/emporia_vue/__init__.py", line 373, in update_sensors await parse_flattened_usage_data( File "/config/custom_components/emporia_vue/__init__.py", line 420, in parse_flattened_usage_data local_time = change_time_to_local(data_time, info.time_zone) File "/config/custom_components/emporia_vue/__init__.py", line 564, in change_time_to_local tz_info = dateutil.tz.gettz(tz_string) 
```

**Comment by ronron90** [comment]
I'm getting the same error

**Comment by ronron90** [comment]
> Hello, I just installed the integration. I am getting an unexpected error when logging in under the service section. Has anyone else seen this? Any fix? Thanks in advance.

I just fixed the issue for me. I reinstall 3 versions back. Then once installed. Installed the update it seems to work now.
