### ISSUE TITLE
Unexpected Error When Trying To Setup Integration

### ISSUE THREAD

**Issue by terminusxx** [magico13/ha-emporia-vue#30]
Was working fine before the api issues, I've reinstalled multiple times and tried both the 3.1 and master builds. Username and password are correct, I've double checked by logging out and back into the app on android.

021-02-21T07:25:44.293538000Z 2021-02-20 21:25:44 ERROR (MainThread) [custom_components.emporia_vue.config_flow] Unexpected exception

2021-02-21T07:25:44.295419000Z Traceback (most recent call last):

2021-02-21T07:25:44.295836000Z   File "/config/custom_components/emporia_vue/config_flow.py", line 79, in async_step_user

2021-02-21T07:25:44.296287000Z     info = await validate_input(self.hass, user_input)

2021-02-21T07:25:44.296712000Z   File "/config/custom_components/emporia_vue/config_flow.py", line 49, in validate_input

2021-02-21T07:25:44.297073000Z     if not await hub.authenticate(data[CONF_EMAIL], data[CONF_PASSWORD]):

2021-02-21T07:25:44.297418000Z   File "/config/custom_components/emporia_vue/config_flow.py", line 39, in authenticate

2021-02-21T07:25:44.297784000Z     result = await loop.run_in_executor(None, self.vue.login, username, password)

2021-02-21T07:25:44.298128000Z   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

2021-02-21T07:25:44.298476000Z     result = self.fn(*self.args, **self.kwargs)

2021-02-21T07:25:44.298871000Z   File "/usr/local/lib/python3.8/site-packages/pyemvue/pyemvue.py", line 153, in login

2021-02-21T07:25:44.299286000Z     self.cognito.authenticate(password=password)

2021-02-21T07:25:44.299668000Z   File "/usr/local/lib/python3.8/site-packages/warrant/__init__.py", line 382, in authenticate

2021-02-21T07:25:44.300038000Z     tokens = aws.authenticate_user()

2021-02-21T07:25:44.300408000Z   File "/usr/local/lib/python3.8/site-packages/warrant/aws_srp.py", line 203, in authenticate_user

2021-02-21T07:25:44.300770000Z     response = boto_client.initiate_auth(

2021-02-21T07:25:44.301151000Z   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call

2021-02-21T07:25:44.301530000Z     return self._make_api_call(operation_name, kwargs)

2021-02-21T07:25:44.301994000Z   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 661, in _make_api_call

2021-02-21T07:25:44.302515000Z     raise error_class(parsed_response, operation_name)

2021-02-21T07:25:44.302955000Z botocore.errorfactory.UserNotFoundException: An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.

**Comment by magico13** [comment]
Interesting that the core error is a UserNotFoundException. Are you in the US or another region? Did you change any account settings recently and you're using the full email address as listed in the Account settings in the app?

**Comment by terminusxx** [comment]
So I figured it out, appears that the email address input is case sensitive, I was using a capital letter to start my email address out of habit. Wild, everything works now that I switched to lowercase, Thanks for your help and your great work on this integration!

**Comment by magico13** [comment]
Interesting, that's something I'll have to keep an eye out for in the future. Glad it's working now!

**Comment by Jpereyra316** [comment]
I encountered this issue as well. Luckily I was able to find this issue here pretty easily. Is it possible to add a warning/info on the login setup prompt?
