### ISSUE TITLE
No channels found

### ISSUE THREAD

**Issue by mikedm139** [magico13/ha-emporia-vue#42]
I'm not sure if this is the same issue as #33. If it is, I can add my data points there. My Emporia integration has been offline for the last week or so. I have restarted HA several times, reloaded the integration, updated HA (currently running core-2021.5.0) without improvement. Below is the log lines that are generated.
```
2021-05-06 07:39:21 WARNING (MainThread) [custom_components.emporia_vue.sensor] No channels found during update
2021-05-06 07:39:21 WARNING (MainThread) [custom_components.emporia_vue.sensor] No channels found during update
2021-05-06 07:39:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in async_add_entities
tasks = [
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in <listcomp>
tasks = [
File "/config/custom_components/emporia_vue/sensor.py", line 128, in <genexpr>
CurrentVuePowerSensor(coordinator_1min, id)
File "/config/custom_components/emporia_vue/sensor.py", line 171, in __init__
if self._channel is None:
AttributeError: 'CurrentVuePowerSensor' object has no attribute '_channel'
```
Based on the discussion in #33, I reinstalled the integration using the `master` branch. The problem remains but more information was included in the logging:
```
2021-05-06 10:00:31 WARNING (MainThread) [custom_components.emporia_vue] 1min Update data: {'14681-1,2,3-1MIN': {'device_gid': 14681, 'channel_num': '1,2,3', 'usage': 755, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153acf3b9550>}, '14681-1-1MIN': {'device_gid': 14681, 'channel_num': '1', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-2-1MIN': {'device_gid': 14681, 'channel_num': '2', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-3-1MIN': {'device_gid': 14681, 'channel_num': '3', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-4-1MIN': {'device_gid': 14681, 'channel_num': '4', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-5-1MIN': {'device_gid': 14681, 'channel_num': '5', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-6-1MIN': {'device_gid': 14681, 'channel_num': '6', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-7-1MIN': {'device_gid': 14681, 'channel_num': '7', 'usage': 0, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-8-1MIN': {'device_gid': 14681, 'channel_num': '8', 'usage': 37, 'scale': '1MIN', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-1,2,3-1D': {'device_gid': 14681, 'channel_num': '1,2,3', 'usage': 11.787, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153acf3b9550>}, '14681-MainsFromGrid-1D': {'device_gid': 14681, 'channel_num': 'MainsFromGrid', 'usage': 11.787, 'scale': '1D', 'info': None}, '14681-MainsToGrid-1D': {'device_gid': 14681, 'channel_num': 'MainsToGrid', 'usage': 0.0, 'scale': '1D', 'info': None}, '14681-1-1D': {'device_gid': 14681, 'channel_num': '1', 'usage': 0.0, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-2-1D': {'device_gid': 14681, 'channel_num': '2', 'usage': 0.0, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-3-1D': {'device_gid': 14681, 'channel_num': '3', 'usage': 0.818, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-4-1D': {'device_gid': 14681, 'channel_num': '4', 'usage': 0.0, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-5-1D': {'device_gid': 14681, 'channel_num': '5', 'usage': 0.0, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-6-1D': {'device_gid': 14681, 'channel_num': '6', 'usage': 0.0, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-7-1D': {'device_gid': 14681, 'channel_num': '7', 'usage': 2.731, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-8-1D': {'device_gid': 14681, 'channel_num': '8', 'usage': 0.407, 'scale': '1D', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-1,2,3-1MON': {'device_gid': 14681, 'channel_num': '1,2,3', 'usage': 156.328, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153acf3b9550>}, '14681-MainsFromGrid-1MON': {'device_gid': 14681, 'channel_num': 'MainsFromGrid', 'usage': 156.328, 'scale': '1MON', 'info': None}, '14681-MainsToGrid-1MON': {'device_gid': 14681, 'channel_num': 'MainsToGrid', 'usage': 0.0, 'scale': '1MON', 'info': None}, '14681-1-1MON': {'device_gid': 14681, 'channel_num': '1', 'usage': 0.0, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-2-1MON': {'device_gid': 14681, 'channel_num': '2', 'usage': 0.0, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-3-1MON': {'device_gid': 14681, 'channel_num': '3', 'usage': 9.368, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-4-1MON': {'device_gid': 14681, 'channel_num': '4', 'usage': 3.051, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-5-1MON': {'device_gid': 14681, 'channel_num': '5', 'usage': 16.947, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-6-1MON': {'device_gid': 14681, 'channel_num': '6', 'usage': 1.705, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-7-1MON': {'device_gid': 14681, 'channel_num': '7', 'usage': 26.079, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}, '14681-8-1MON': {'device_gid': 14681, 'channel_num': '8', 'usage': 4.494, 'scale': '1MON', 'info': <pyemvue.device.VueDevice object at 0x153ad54f5880>}}
2021-05-06 10:00:31 WARNING (MainThread) [custom_components.emporia_vue.sensor] No channel found for device_gid 14681 and channel_num MainsFromGrid
2021-05-06 10:00:33 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in async_add_entities
tasks = [
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in <listcomp>
tasks = [
File "/config/custom_components/emporia_vue/sensor.py", line 31, in <genexpr>
CurrentVuePowerSensor(coordinator_1min, id)
File "/config/custom_components/emporia_vue/sensor.py", line 63, in __init__
raise RuntimeError(
RuntimeError: No channel found for device_gid 14681 and channel_num MainsFromGrid
```

**Comment by magico13** [comment]
It looks like this is the same as #44. Do you happen to have solar?

**Comment by mikedm139** [comment]
I noticed #41 after I submitted this issue. I was about to comment that they're likely related if not the same.
I do in fact have a solar install.  I have the Vue installed to monitor the mains and 8 (non-solar) circuits.

**Comment by magico13** [comment]
Alright, I'm gonna close this as a duplicate to that one if you don't mind just to track them in one place. I'll try to get a fix for that out later today.
