### ISSUE TITLE
1min sensors unavailable since the backing API change

### ISSUE THREAD

**Issue by markrietveld** [magico13/ha-emporia-vue#65]
I updated to 0.6.4, but not everything is working for me yet. I have a Vue Utility connect, and 4 plugs. All of them report the 1 day and 1 month sensor.

I tried uninstalling the integration completely, and reinstalling. That didn't fix the issue either. I see this in the logs:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/emporia_vue/sensor.py:158
Integration: Emporia Vue (documentation)
First occurred: 12:40:21 PM (1 occurrences)
Last logged: 12:40:21 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/emporia_vue/sensor.py", line 91, in state
    return self.scale_usage(usage)
  File "/config/custom_components/emporia_vue/sensor.py", line 158, in scale_usage
    usage = round(usage, 3)
TypeError: type NoneType doesn't define __round__ method
```

and also:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/emporia_vue/sensor.py:150
Integration: Emporia Vue (documentation)
First occurred: 12:40:20 PM (1 occurrences)
Last logged: 12:40:20 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/emporia_vue/sensor.py", line 91, in state
    return self.scale_usage(usage)
  File "/config/custom_components/emporia_vue/sensor.py", line 150, in scale_usage
    usage = round(60 * 1000 * usage)  # convert from kwh to w rate
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by magico13** [comment]
Not sure why it'd be None and not a number but that should be easy enough to fix. Will take care of it tonight!

**Comment by SteveB0005** [comment]
Hi @magico13, I want to thank you for all your work on this!!! I just signed up on GitHub to ask about the 1m with my custom_integrations install, but as with every other time something on this didn't work right (due to Emporia changing stuff on you), you are already on it! Thank you!

**Comment by Sc00bs110** [comment]
Happening for me as well. 
![image](https://user-images.githubusercontent.com/63442834/130142801-f645b34a-3031-4642-8081-4f380bddefe8.png)

From the log

This error originated from a custom integration.

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:192
Integration: Emporia Vue (documentation)
First occurred: 10:54:08 PM (5 occurrences)
Last logged: 10:55:55 PM

Exception while setting up Emporia Vue. Will retry. 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/customers/29868/devices?detailed=true&hierarchy=true

**Comment by magico13** [comment]
@Sc00bs110 you've got a different issue due to being on an old version. Update to 0.6.4, restart home assistant, then check again. Hopefully the update is all you need.

**Comment by SteveB0005** [comment]
@markrietveld, what version are you on (Core and Front End)? I just upgraded my container from 2021.6.5 to 2021.8.8 and associated front end, and I now have my 1m entities back and no errors in the logs.

**Comment by Sc00bs110** [comment]
Thanks Magico13, updated and is working now

**Comment by magico13** [comment]
@markrietveld Try installing the master branch build, it has a potential fix for this in it. Go into HACS, then choose Reinstall on the integration, then for the version scroll down to "master". You'll have to restart Home Assistant before it finishes the update but hopefully that fixes this error.

**Comment by markrietveld** [comment]
Confirmed, reinstalling from master got my 1 min sensors working again.
Thanks!

**Comment by markrietveld** [comment]
@SteveB0005 I was on 2021.8.6 when the 1 min sensors disappeared. Upgrading to 2021.8.8 didn't fix it

**Comment by MichaelB2018** [comment]
I have the same problem,  it only fixed it for the main sensor (incoming sensor), but not for my individual sensors. There I still don't have the 1 MIN sensors back.

**Comment by yodashut** [comment]
I had the same issue.  After rebooting Home Assistant and reloading the integration it resolved itself.

**Comment by Phara0h** [comment]
After rebooting my 1min sensors showed up but the "energy" panel wont let me select anything other 1d or 1mon sensors. Is this working as attended?

**Comment by magico13** [comment]
> After rebooting my 1min sensors showed up but the "energy" panel wont let me select anything other 1d or 1mon sensors. Is this working as attended?

The home assistant energy dashboard only works with energy sensors and not power sensors. You should choose the 1 Day sensors for the most accuracy.

The dashboard looks like the Tesla energy flow diagram but doesn't work the same, it just shows daily totals.

**Comment by Phara0h** [comment]
> > After rebooting my 1min sensors showed up but the "energy" panel wont let me select anything other 1d or 1mon sensors. Is this working as attended?
> 
> The home assistant energy dashboard only works with energy sensors and not power sensors. You should choose the 1 Day sensors for the most accuracy.
> 
> The dashboard looks like the Tesla energy flow diagram but doesn't work the same, it just shows daily totals.

So there would be pretty much no point to take 1min sensors / 60 to convert it to kWh since the energy panel would not show that kind of accuracy?

**Comment by magico13** [comment]
It works by looking at how much the energy sensor goes up at each hour, so you're correct that it won't make a difference. The 1 Day sensors already integrate the 1 minute sensor data into them so that's why I suggest using them.

**Comment by armdan** [comment]
The 1-minute sensor is important for some automations and it shows unavailable

**Comment by donparlor** [comment]
That problem seems to be back after 2023-08 release. Anyone having this issue?

**Comment by ah-blake** [comment]
> That problem seems to be back after 2023-08 release. Anyone having this issue?

I installed the integration for the first time today and I can only see the 1D/1MON sensors, but the 1MIN ones are available elsewhere to dashboard

**Comment by pjurczy** [comment]
I just installed emporia vue integration a few days ago, and 1MIN sensors appear to be missing on some home assistant runs. Restarting solves the problem, but it appears as if 1MIN sensor is flaky at least for me.

**Comment by JesseStLaurent** [comment]
I am experiencing the same issue with 1MIN sensors. They all say this entity is no longer being provided by the emporia vue integration.

**Comment by donparlor** [comment]
Still no update... sadly. It makes Emporia much less interesting rather useless for my dryer automation.

**Comment by magico13** [comment]
There are other active issues open for this, eg #232. Unfortunately I do not have this problem so I haven't been able to track it down but I am in the middle of a rewrite of how the sensors are created and updated in an attempt to improve this issue. If you need reliable data though you're not going to get it from their cloud and I recommend reflashing the hardware with ESPHome.
