### ISSUE TITLE
No individual sensors

### ISSUE THREAD

**Issue by jscherry** [magico13/ha-emporia-vue#85]
I've installed the integration but am only seeing three entities; minute, day, and month. I'm using the emporia with two main clamps and 16 50a clamps. Shouldn't I be seeing individual sensors for these clamps? Thanks

**Comment by jscherry** [comment]
Here are the errors I'm getting in home assistant
This error originated from a custom integration.

Logger: custom_components.emporia_vue
Source: custom_components/emporia_vue/__init__.py:149
Integration: Emporia Vue (documentation)
First occurred: 6:48:21 PM (29 occurrences)
Last logged: 7:16:32 PM

Unexpected error fetching sensor data: '75143-1-1D'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/emporia_vue/__init__.py", line 149, in async_update_day_sensors
    and last_day_data[day_id]
KeyError: '75143-1-1D'
